root: ./

structure:
  readme: ./README.md
  summary: ./SUMMARY.md

redirects:
  develop/public-endpoints: nodes/public-endpoints.md
  guides: developers/README.md
  develop/cheat-sheet: developers/README.md
  develop/tech-concepts: developers/README.md
  nodes/RunNode/testnet: infra/run-node.md
  develop/tools: developers/biyaliquidd/README.md
  develop/guides: developers/README.md
  develop/modules: developers-native/README.md
  develop/modules/Core/auth: developers-native/core/auth/README.md
  develop/guides/cosmwasm-dapps: developers-cosmwasm/create-uis-guide.md
  getting-started: README.md
  getting-started/wallet: defi/wallet/README.md
  getting-started/wallet/create-a-wallet: defi/wallet/create.md
  getting-started/wallet/accounts: defi/wallet/accounts.md
  getting-started/wallet/staking: defi/staking.md
  getting-started/wallet/governance: defi/governance.md
  getting-started/wallet/auction: defi/auction.md
  guides/bridge: defi/bridge/README.md
  getting-started/token-standards: defi/tokens/README.md
  getting-started/token-standards/biya-coin: defi/tokens/biya-coin.md
  getting-started/token-standards/token-factory: defi/tokens/token-factory.md
  getting-started/token-standards/cw20-standard: defi/tokens/cw20-standard.md
  getting-started/transactions: defi/transactions.md
  getting-started/transactions/gas-and-fees: defi/transaction-fees.md
  nodes/getting-started/interact-with-a-node: infra/interact-node-rest.md
  nodes/getting-started/running-a-node: infra/run-node.md
  nodes/getting-started/running-a-node/1.-setting-up-the-keyring: infra/set-up-keyring.md
  nodes/getting-started/running-a-node/join-a-network: infra/join-a-network.md
  nodes/getting-started/running-a-node/cosmovisor: infra/cosmovisor.md
  nodes/getting-started/running-a-node/upgrade-your-node: infra/upgrade-node.md
  nodes/validators: infra/validator-mainnet/README.md
  nodes/validators/mainnet: infra/validator-mainnet/README.md
  nodes/validators/mainnet/peggo: infra/validator-mainnet/peggo.md
  nodes/validators/mainnet/canonical-chain-upgrades: infra/validator-mainnet/canonical-chain-upgrade.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10002-rc1: infra/validator-mainnet/canonical-chain-upgrade-10002-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10002-rc2: infra/validator-mainnet/canonical-chain-upgrade-10002-rc2.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10003-rc1: infra/validator-mainnet/canonical-chain-upgrade-10003-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10004-rc1: infra/validator-mainnet/canonical-chain-upgrade-10004-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10004-rc1-patch: infra/validator-mainnet/canonical-chain-upgrade-10004-rc1-patch.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10005-rc1: infra/validator-mainnet/canonical-chain-upgrade-10005-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10006-rc1: infra/validator-mainnet/canonical-chain-upgrade-10006-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10007-rc1: infra/validator-mainnet/canonical-chain-upgrade-10007-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10008: infra/validator-mainnet/canonical-chain-upgrade-10008.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10009: infra/validator-mainnet/canonical-chain-upgrade-10009.md
  nodes/validators/mainnet/canonical-chain-upgrades/upgrade-to-v1.10: infra/validator-mainnet/canonical-chain-upgrade-v1.10.0.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10011: infra/validator-mainnet/canonical-chain-upgrade-v1.11.0.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1-12: infra/validator-mainnet/canonical-chain-upgrade-v1.12.0.md
  nodes/validators/mainnet/canonical-chain-upgrades/upgrade-to-v1.12.1: infra/validator-mainnet/canonical-chain-upgrade-v1.12.1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.13.0: infra/validator-mainnet/canonical-chain-upgrade-1.13.0.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.13.2: infra/validator-mainnet/canonical-chain-upgrade-1.13.2.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.13.3: infra/validator-mainnet/canonical-chain-upgrade-1.13.3.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.14.0: infra/validator-mainnet/canonical-chain-upgrade-1.14.0.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.14.1: infra/validator-mainnet/canonical-chain-upgrade-1.14.1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.15.0: infra/validator-mainnet/canonical-chain-upgrade-1.15.0.md
  nodes/validators/testnet: infra/validator-testnet/README.md
  nodes/validators/testnet/testnet-peggo: infra/validator-testnet/peggo.md
  nodes/validators/cosmosvisor: infra/cosmovisor.md
  nodes/public-endpoints: infra/public-endpoints.md
  nodes/private-nodes: infra/premium-endpoints.md
  developers/modules: developers-native/README.md
  developers/modules/biyaliquid: developers-native/biyaliquid/README.md
  developers/modules/biyaliquid/auction: developers-native/biyaliquid/auction/README.md
  developers/modules/biyaliquid/auction/01_state: developers-native/biyaliquid/auction/01_state.md
  developers/modules/biyaliquid/auction/02_messages: developers-native/biyaliquid/auction/02_messages.md
  developers/modules/biyaliquid/auction/03_end_block: developers-native/biyaliquid/auction/03_end_block.md
  developers/modules/biyaliquid/auction/04_events: developers-native/biyaliquid/auction/04_events.md
  developers/modules/biyaliquid/auction/05_params: developers-native/biyaliquid/auction/05_params.md
  developers/modules/biyaliquid/auction/99_errors: developers-native/biyaliquid/auction/99_errors.md
  developers/modules/biyaliquid/exchange: developers-native/biyaliquid/exchange/README.md
  developers/modules/biyaliquid/exchange/00_derivative_market_concepts: developers-native/biyaliquid/exchange/00_derivative_market_concepts.md
  developers/modules/biyaliquid/exchange/01_spot_market_concepts: developers-native/biyaliquid/exchange/01_spot_market_concepts.md
  developers/modules/biyaliquid/exchange/02_binary_options_markets: developers-native/biyaliquid/exchange/02_binary_options_markets.md
  developers/modules/biyaliquid/exchange/02_other_concepts: developers-native/biyaliquid/exchange/02_other_concepts.md
  developers/modules/biyaliquid/exchange/03_state: developers-native/biyaliquid/exchange/03_state.md
  developers/modules/biyaliquid/exchange/04_state_transitions: developers-native/biyaliquid/exchange/04_state_transitions.md
  developers/modules/biyaliquid/exchange/05_messages: developers-native/biyaliquid/exchange/05_messages.md
  developers/modules/biyaliquid/exchange/06_proposals: developers-native/biyaliquid/exchange/06_proposals.md
  developers/modules/biyaliquid/exchange/07_begin_block: developers-native/biyaliquid/exchange/07_begin_block.md
  developers/modules/biyaliquid/exchange/08_end_block: developers-native/biyaliquid/exchange/08_end_block.md
  developers/modules/biyaliquid/exchange/09_events: developers-native/biyaliquid/exchange/09_events.md
  developers/modules/biyaliquid/exchange/10_params: developers-native/biyaliquid/exchange/10_params.md
  developers/modules/biyaliquid/exchange/11_msg_privileged_execute_contract: developers-native/biyaliquid/exchange/11_msg_privileged_execute_contract.md
  developers/modules/biyaliquid/exchange/99_errors: developers-native/biyaliquid/exchange/99_errors.md
  developers/modules/biyaliquid/insurance: developers-native/biyaliquid/insurance/README.md
  developers/modules/biyaliquid/insurance/01_state: developers-native/biyaliquid/insurance/01_state.md
  developers/modules/biyaliquid/insurance/02_state_transitions: developers-native/biyaliquid/insurance/02_state_transitions.md
  developers/modules/biyaliquid/insurance/03_messages: developers-native/biyaliquid/insurance/03_messages.md
  developers/modules/biyaliquid/insurance/04_end_block: developers-native/biyaliquid/insurance/04_end_block.md
  developers/modules/biyaliquid/insurance/05_events: developers-native/biyaliquid/insurance/05_events.md
  developers/modules/biyaliquid/insurance/06_params: developers-native/biyaliquid/insurance/06_params.md
  developers/modules/biyaliquid/insurance/07_future_improvements: developers-native/biyaliquid/insurance/07_future_improvements.md
  developers/modules/biyaliquid/insurance/99_errors: developers-native/biyaliquid/insurance/99_errors.md
  developers/modules/biyaliquid/ocr: developers-native/biyaliquid/ocr/README.md
  developers/modules/biyaliquid/ocr/01_concepts: developers-native/biyaliquid/ocr/01_concepts.md
  developers/modules/biyaliquid/ocr/02_state: developers-native/biyaliquid/ocr/02_state.md
  developers/modules/biyaliquid/ocr/03_messages: developers-native/biyaliquid/ocr/03_messages.md
  developers/modules/biyaliquid/ocr/04_proposals: developers-native/biyaliquid/ocr/04_proposals.md
  developers/modules/biyaliquid/ocr/05_begin_block: developers-native/biyaliquid/ocr/05_begin_block.md
  developers/modules/biyaliquid/ocr/06_hooks: developers-native/biyaliquid/ocr/06_hooks.md
  developers/modules/biyaliquid/ocr/07_events: developers-native/biyaliquid/ocr/07_events.md
  developers/modules/biyaliquid/ocr/08_params: developers-native/biyaliquid/ocr/08_params.md
  developers/modules/biyaliquid/ocr/99_errors: developers-native/biyaliquid/ocr/99_errors.md
  developers/modules/biyaliquid/oracle: developers-native/biyaliquid/oracle/README.md
  developers/modules/biyaliquid/oracle/01_state: developers-native/biyaliquid/oracle/01_state.md
  developers/modules/biyaliquid/oracle/02_keeper: developers-native/biyaliquid/oracle/02_keeper.md
  developers/modules/biyaliquid/oracle/03_messages: developers-native/biyaliquid/oracle/03_messages.md
  developers/modules/biyaliquid/oracle/04_proposals: developers-native/biyaliquid/oracle/04_proposals.md
  developers/modules/biyaliquid/oracle/05_events: developers-native/biyaliquid/oracle/05_events.md
  developers/modules/biyaliquid/oracle/06_future_improvements: developers-native/biyaliquid/oracle/06_future_improvements.md
  developers/modules/biyaliquid/oracle/99_errors: developers-native/biyaliquid/oracle/99_errors.md
  developers/modules/biyaliquid/peggy: developers-native/biyaliquid/peggy/README.md
  developers/modules/biyaliquid/peggy/01_definitions: developers-native/biyaliquid/peggy/01_definitions.md
  developers/modules/biyaliquid/peggy/02_workflow: developers-native/biyaliquid/peggy/02_workflow.md
  developers/modules/biyaliquid/peggy/03_state: developers-native/biyaliquid/peggy/03_state.md
  developers/modules/biyaliquid/peggy/04_messages: developers-native/biyaliquid/peggy/04_messages.md
  developers/modules/biyaliquid/peggy/05_slashing: developers-native/biyaliquid/peggy/05_slashing.md
  developers/modules/biyaliquid/peggy/06_end_block: developers-native/biyaliquid/peggy/06_end_block.md
  developers/modules/biyaliquid/peggy/07_events: developers-native/biyaliquid/peggy/07_events.md
  developers/modules/biyaliquid/peggy/08_params: developers-native/biyaliquid/peggy/08_params.md
  developers/modules/biyaliquid/peggy/09_relay_semantics: developers-native/biyaliquid/peggy/09_relay_semantics.md
  developers/modules/biyaliquid/peggy/10_future_improvements: developers-native/biyaliquid/peggy/10_future_improvements.md
  developers/modules/biyaliquid/peggy/99_errors: developers-native/biyaliquid/peggy/99_errors.md
  developers/modules/biyaliquid/permissions: developers-native/biyaliquid/permissions/README.md
  developers/modules/biyaliquid/permissions/01_concepts: developers-native/biyaliquid/permissions/01_concepts.md
  developers/modules/biyaliquid/permissions/02_state: developers-native/biyaliquid/permissions/02_state.md
  developers/modules/biyaliquid/permissions/03_state_transitions: developers-native/biyaliquid/permissions/03_state_transitions.md
  developers/modules/biyaliquid/permissions/99_errors: developers-native/biyaliquid/permissions/99_errors.md
  developers/modules/biyaliquid/tokenfactory: developers-native/biyaliquid/tokenfactory/README.md
  developers/modules/biyaliquid/tokenfactory/01_concepts: developers-native/biyaliquid/tokenfactory/01_concepts.md
  developers/modules/biyaliquid/tokenfactory/02_state: developers-native/biyaliquid/tokenfactory/02_state.md
  developers/modules/biyaliquid/tokenfactory/03_messages: developers-native/biyaliquid/tokenfactory/03_messages.md
  developers/modules/biyaliquid/tokenfactory/04_events: developers-native/biyaliquid/tokenfactory/04_events.md
  developers/modules/biyaliquid/tokenfactory/05_params: developers-native/biyaliquid/tokenfactory/05_params.md
  developers/modules/biyaliquid/tokenfactory/99_errors: developers-native/biyaliquid/tokenfactory/99_errors.md
  developers/modules/biyaliquid/wasmx: developers-native/biyaliquid/wasmx/README.md
  developers/modules/biyaliquid/wasmx/01_concepts: developers-native/biyaliquid/wasmx/01_concepts.md
  developers/modules/biyaliquid/wasmx/02_data: developers-native/biyaliquid/wasmx/02_data.md
  developers/modules/biyaliquid/wasmx/03_proposals: developers-native/biyaliquid/wasmx/03_proposals.md
  developers/modules/biyaliquid/wasmx/04_messages: developers-native/biyaliquid/wasmx/04_messages.md
  developers/modules/biyaliquid/wasmx/05_params: developers-native/biyaliquid/wasmx/05_params.md
  developers/modules/biyaliquid/wasmx/99_errors: developers-native/biyaliquid/wasmx/99_errors.md
  developers/modules/biyaliquid/lanes: developers-native/biyaliquid/lanes/README.md
  developers/modules/biyaliquid/txfees: developers-native/biyaliquid/txfees/README.md
  developers/modules/core: developers-native/core/README.md
  developers/modules/core/auth: developers-native/core/auth/README.md
  developers/modules/core/authz: developers-native/core/authz/README.md
  developers/modules/core/bank: developers-native/core/bank/README.md
  developers/modules/core/consensus: developers-native/core/consensus/README.md
  developers/modules/core/crisis: developers-native/core/crisis/README.md
  developers/modules/core/distribution: developers-native/core/distribution/README.md
  developers/modules/core/evidence: developers-native/core/evidence/README.md
  developers/modules/core/feegrant: developers-native/core/feegrant/README.md
  developers/modules/core/gov: developers-native/core/gov/README.md
  developers/modules/core/group: developers-native/core/group/README.md
  developers/modules/core/mint: developers-native/core/mint/README.md
  developers/modules/core/nft: developers-native/core/nft/README.md
  developers/modules/core/params: developers-native/core/params/README.md
  developers/modules/core/slashing: developers-native/core/slashing/README.md
  developers/modules/core/staking: developers-native/core/staking/README.md
  developers/modules/core/upgrade: developers-native/core/upgrade/README.md
  developers/modules/core/circuit: developers-native/core/circuit/README.md
  developers/modules/core/genutil: developers-native/core/genutil/README.md
  developers/exchange-developers: developers-defi/README.md
  developers/getting-started/guides/calculations: developers-defi/calculate-min-price-tick-size.md
  developers/getting-started/guides/calculations/min-price-tick-size: developers-defi/calculate-min-price-tick-size.md
  developers/getting-started/guides/calculations/min-quantity-tick-size: developers-defi/min-quantity-tick-size.md
  developers/getting-started/guides/testnet-faucet-integration: developers-defi/testnet-faucet-integration.md
  guides/launch-a-token: developers-defi/token-launch.md
  guides/launch-a-market: developers-defi/market-launch.md
  guides/denom-metadata: developers-defi/denom-and-bank.md
  developers/exchange-developers/provider-oracle: developers-defi/provider-oracle.md
  developers/cosmwasm-developers: developers-cosmwasm/README.md
  developers/cosmwasm-developers/your-first-smart-contract: developers-cosmwasm/your-first-smart-contract-guide.md
  developers-cosmwasm/your-first-smart-contract-guide: developers-cosmwasm/smart-contracts/your-first-smart-contract.md
  developers/cosmwasm-developers/guides: developers-cosmwasm/local-development-guide.md
  developers/cosmwasm-developers/guides/local-development: developers-cosmwasm/local-development-guide.md
  developers/cosmwasm-developers/guides/mainnet-deployment: developers-cosmwasm/mainnet-deployment-guide.md
  developers/cosmwasm-developers/guides/whitelisting-deployment-address: developers-cosmwasm/whitelisting-deployment-address-guide.md
  developers/cosmwasm-developers/guides/create-your-swap-contract: developers-cosmwasm/create-your-swap-contract-guide.md
  developers/cosmwasm-developers/guides/creating-uis: developers-cosmwasm/create-uis-guide.md
  developers/cosmwasm-developers/cosmwasm-any: developers-cosmwasm/cosmwasm-any.md
  developers/cosmwasm-developers/page-1: developers-cosmwasm/cw20-adapter.md
  developers/cosmwasm-developers/biyaliquid-test-tube: developers-cosmwasm/biyaliquid-test-tube.md
  developers/evm-developers: developers-evm/README.md
  developers-evm/your-first-smart-contract: developers-evm/smart-contracts/README.md
  developers/evm-developers/your-first-smart-contract: developers-evm/smart-contracts/README.md
  developers/evm-developers/guides: developers-evm/smart-contracts/README.md
  developers-evm/testnet-deployment: developers-evm/smart-contracts/README.md
  developers/evm-developers/guides/testnet-deployment: developers-evm/smart-contracts/README.md
  developers/evm-developers/technical-information: developers-evm/network-information.md
  developers/evm-developers/technical-information/network-information: developers-evm/network-information.md
  developers/evm-developers/technical-information/evm-equivalence: developers-evm/evm-equivalence.md
  developers/evm-developers/technical-information/multivm-token-standard: developers-evm/multivm-token-standard.md
  developers/evm-developers/technical-information/precompiles: developers-evm/precompiles.md
  developers/evm-developers/technical-information/precompiles/bank-precompile: developers-evm/bank-precompile.md
  developers/evm-developers/technical-information/precompiles/exchange-precompile: developers-evm/exchange-precompile.md
  developers/evm-developers/technical-information/erc20-module: developers-evm/erc20-module.md
  developers/evm-developers/technical-information/infrastructure-and-tooling: developers-evm/infrastructure-and-tooling.md
  developers/getting-started: developers/README.md
  developers/getting-started/guides: developers/testnet-proposals.md
  developers/getting-started/guides/testnet-proposals: developers/testnet-proposals.md
  developers/getting-started/guides/convert-addresses: developers/convert-addresses.md
  toolkits: developers/biyaliquidd/README.md
  toolkits/biyaliquidd: developers/biyaliquidd/README.md
  toolkits/biyaliquidd/install-biyaliquidd: developers/biyaliquidd/install.md
  toolkits/biyaliquidd/using-biyaliquidd: developers/biyaliquidd/use.md
  toolkits/biyaliquidd/advanced: developers/biyaliquidd/advanced.md
